library(arules)
rules <- apriori(as.matrix(my_movies[,6:15],parameter=list(support=0.2, confidence = 0.5,minlen=3)))
inspect(head(sort(rules, by = "lift")))  
head(quality(rules))
plot(rules,method = "scatterplot")
plot(rules, method = "grouped")
plot(rules,method = "graph")
